# This file was generated by GoReleaser. DO NOT EDIT.
class Qtrn < Formula
  desc "qtrn is a tool for printing financial markets data to the console and writing data to files."
  homepage "https://github.com/piquette/qtrn"
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/piquette/qtrn/releases/download/v0.0.9/qtrn_0.0.9_darwin_amd64.tar.gz"
    sha256 "511878b74f739268993895c244802fa11b5b22ad955d834e093419a840d5b656"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/piquette/qtrn/releases/download/v0.0.9/qtrn_0.0.9_linux_amd64.tar.gz"
      sha256 "99af3142e8756b4b5a9f7fff7fcceb720cd7f8af3f6ed86b0a36378b402b9acd"
    end
  end

  def install
    bin.install "qtrn"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/qtrn.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/qtrn.log</string>
  </dict>
</plist>

  EOS
  end
end
